export const STEP_PROGRESS_COMPLETED_COLOR = "#22c55e";
export const STEP_PROGRESS_TRACK_COLOR = "#d1d5db";
export const STEP_PROGRESS_NUMBER_COLOR = "#6b7280";
export const STEP_PROGRESS_LABEL_COLOR = "#374151";
export const STEP_PROGRESS_CIRCLE_SIZE = 40;
export const STEP_PROGRESS_LINE_HEIGHT = 3;
export const STEP_PROGRESS_VERTICAL_CONNECTOR_MIN_HEIGHT = 40;
